services:

  postgres:
    image: postgres
    volumes:
      - ./db-postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=xacademy
