version: '3.8'
services:
  postgres:
    image: postgres
    volumes:
      - db-postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:${DB_PORT}
    environment:
      - DATABASE_HOST=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}

volumes:
  db-postgres:
